######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 9 19:20:19 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialog.h function.h interface.h
FORMS += dialog.ui
SOURCES += dialog.cpp function.cpp interface.cpp main.cpp
